/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.synapse.subpanels;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author sanukadev
 */
public class BloodRequestSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodRequestSubPanel
     */
    public BloodRequestSubPanel() {
        initComponents();
        styles();
    }

    private void styles() {
//        pendingLabel.putClientProperty(FlatClientProperties.STYLE, ""
//                + "background: #fff5d2;"
//                + "foreground: #e68c00;"
//                + "borderArc: 999;"
//                + "padding: 5,10,5,10;"
//        );
//        pendingLabel.setOpaque(true);

     FlatSVGIcon peopleIcon = new FlatSVGIcon("com/dev/synapse/assets/clock-icon.svg", 20, 20);
     iconLabel.setIcon(peopleIcon);
     
     bloodTypeLabel.putClientProperty(FlatClientProperties.STYLE, "arc:999");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bloodTypeLabel = new javax.swing.JLabel();
        urgencyLevelLabel = new javax.swing.JLabel();
        pendingLabel3 = new javax.swing.JLabel();

        pendingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel1.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setText("Pending");
        pendingLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setOpaque(true);

        setBackground(new java.awt.Color(234, 234, 234));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("4");

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Request #REQ -");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("000");

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Units");

        iconLabel.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("2025-08-17");

        bloodTypeLabel.setBackground(new java.awt.Color(204, 255, 204));
        bloodTypeLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        bloodTypeLabel.setForeground(new java.awt.Color(0, 153, 51));
        bloodTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setText("O+");
        bloodTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setOpaque(true);

        urgencyLevelLabel.setBackground(new java.awt.Color(255, 204, 204));
        urgencyLevelLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        urgencyLevelLabel.setForeground(new java.awt.Color(255, 0, 0));
        urgencyLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setText("High");
        urgencyLevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setOpaque(true);

        pendingLabel3.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel3.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel3.setText("Pending");
        pendingLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel3.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pendingLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pendingLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel pendingLabel1;
    private javax.swing.JLabel pendingLabel3;
    private javax.swing.JLabel urgencyLevelLabel;
    // End of variables declaration//GEN-END:variables
}
