/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.synapse.subpanels;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author sanukadev
 */
public class BloodInventorySubPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodRequestSubPanel
     */
    public BloodInventorySubPanel() {
        initComponents();
        styles();
    }

    private void styles() {
     
     bloodTypeLabel.putClientProperty(FlatClientProperties.STYLE, "arc:999");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bloodTypeLabel = new javax.swing.JLabel();
        urgencyLevelLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        pendingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel1.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setText("Pending");
        pendingLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setOpaque(true);

        setBackground(new java.awt.Color(234, 234, 234));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("85");

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("of 100 units");

        bloodTypeLabel.setBackground(new java.awt.Color(204, 255, 204));
        bloodTypeLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        bloodTypeLabel.setForeground(new java.awt.Color(0, 153, 51));
        bloodTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setText("O+");
        bloodTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setOpaque(true);

        urgencyLevelLabel.setBackground(new java.awt.Color(255, 204, 204));
        urgencyLevelLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        urgencyLevelLabel.setForeground(new java.awt.Color(255, 0, 0));
        urgencyLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setText("High");
        urgencyLevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setOpaque(true);

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel pendingLabel1;
    private javax.swing.JLabel urgencyLevelLabel;
    // End of variables declaration//GEN-END:variables
}
