/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.synapse.subpanels;

import com.dev.synapse.classes.BloodInventory;
import com.dev.synapse.panel.BankPanel;
import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author sanukadev
 */
public class BloodInventorySubPanel extends javax.swing.JPanel {

    private final BloodInventory bloodInventory;
    private BankPanel bankPanel;

    /**
     * Creates new form BloodRequestSubPanel
     */
    public BloodInventorySubPanel(BloodInventory bloodInventory, BankPanel bankPanel) {
        this.bloodInventory = bloodInventory;
        this.bankPanel = bankPanel;
        initComponents();
        styles();
    }

    public void populateData() {
        bloodTypeLabel.setText(bloodInventory.getBloodType());
        availableUnitsLabel.setText(bloodInventory.getUnitsAvailable());
    }

    private void styles() {
        bloodTypeLabel.putClientProperty(FlatClientProperties.STYLE, "arc:999");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        bloodTypeLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        availableUnitsLabel = new javax.swing.JLabel();

        pendingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel1.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setText("Pending");
        pendingLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setOpaque(true);

        setBackground(new java.awt.Color(234, 234, 234));

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setForeground(new java.awt.Color(255, 0, 0));

        bloodTypeLabel.setBackground(new java.awt.Color(204, 255, 204));
        bloodTypeLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        bloodTypeLabel.setForeground(new java.awt.Color(0, 153, 51));
        bloodTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setText("O+");
        bloodTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("of 100 units");

        availableUnitsLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        availableUnitsLabel.setForeground(new java.awt.Color(51, 51, 51));
        availableUnitsLabel.setText("85");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableUnitsLabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(availableUnitsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableUnitsLabel;
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel pendingLabel1;
    // End of variables declaration//GEN-END:variables
}
