/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.synapse.subpanels;

import com.dev.synapse.classes.PendingRegistrations;
import com.dev.synapse.connection.MySQL;
import com.dev.synapse.panel.AdminPanel;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author sanukadev
 */
public class PendingRegistrationsSubPanel extends javax.swing.JPanel {

    private final PendingRegistrations pendingRegistrations;
    private AdminPanel adminPanel;
    
    private final HashMap<String, Integer> roleMap;

    public PendingRegistrationsSubPanel(PendingRegistrations pendingRegistrations, AdminPanel adminPanel) {
        this.pendingRegistrations = pendingRegistrations;
        this.adminPanel = adminPanel;
        this.roleMap = new HashMap<>();
        initComponents();
        styles();
        loadRoles();
    }

    public void populateData() {
        institutionName.setText(pendingRegistrations.getInsName());
        institutionType.setText(pendingRegistrations.getInsType());
        institutionEmail.setText(pendingRegistrations.getInsEmail());
    }

    private void styles() {
        FlatSVGIcon buildingIcon = new FlatSVGIcon("com/dev/synapse/assets/building-icon.svg", 20, 20);
        institutionName.setIcon(buildingIcon);

        roleComboBox.putClientProperty(FlatClientProperties.STYLE, "arc:15");
    }

    private void loadRoles() {
        try {
            ResultSet rs = MySQL.executeSearch("SELECT * FROM `user_roles`");
            Vector<String> values = new Vector<>();
            values.add("Assign Role");
            roleMap.put("Assign Role", 0);

            while (rs.next()) {
                String roleType = rs.getString("name");
                roleMap.put(roleType, rs.getInt("role_id"));
                values.add(roleType);
            }

            DefaultComboBoxModel dcm = new DefaultComboBoxModel(values);
            roleComboBox.setModel(dcm);

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        roleComboBox = new javax.swing.JComboBox<>();
        approveBtn = new javax.swing.JButton();
        approveBtn1 = new javax.swing.JButton();
        institutionEmail = new javax.swing.JLabel();
        institutionType = new javax.swing.JLabel();
        institutionName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        pendingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel1.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setText("Pending");
        pendingLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setOpaque(true);

        setBackground(new java.awt.Color(234, 234, 234));

        jPanel3.setBackground(new java.awt.Color(244, 244, 244));

        roleComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        approveBtn.setBackground(new java.awt.Color(204, 255, 204));
        approveBtn.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        approveBtn.setForeground(new java.awt.Color(0, 153, 51));
        approveBtn.setText("Approve");
        approveBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)), null));
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        approveBtn1.setBackground(new java.awt.Color(255, 204, 204));
        approveBtn1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        approveBtn1.setForeground(new java.awt.Color(255, 0, 0));
        approveBtn1.setText("Reject");
        approveBtn1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), null));
        approveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtn1ActionPerformed(evt);
            }
        });

        institutionEmail.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        institutionEmail.setForeground(new java.awt.Color(153, 153, 153));
        institutionEmail.setText("chamau@gmail.com");

        institutionType.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        institutionType.setForeground(new java.awt.Color(153, 153, 153));
        institutionType.setText("Hospital");

        institutionName.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        institutionName.setForeground(new java.awt.Color(51, 51, 51));
        institutionName.setText("General Hospital");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(institutionName)
                    .addComponent(institutionEmail)
                    .addComponent(institutionType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(approveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(institutionName)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(institutionType)
                    .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(institutionEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_approveBtnActionPerformed

    private void approveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_approveBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton approveBtn1;
    private javax.swing.JLabel institutionEmail;
    private javax.swing.JLabel institutionName;
    private javax.swing.JLabel institutionType;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pendingLabel1;
    private javax.swing.JComboBox<String> roleComboBox;
    // End of variables declaration//GEN-END:variables
}
