/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.synapse.subpanels;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author sanukadev
 */
public class PendingRegistrationsSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodRequestSubPanel
     */
    public PendingRegistrationsSubPanel() {
        initComponents();
        styles();
    }

    private void styles() {
        FlatSVGIcon buildingIcon = new FlatSVGIcon("com/dev/synapse/assets/building-icon.svg", 20, 20);
        institutionName.setIcon(buildingIcon);
//        approveBtn.putClientProperty(FlatClientProperties.STYLE, "arc:15");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel1 = new javax.swing.JLabel();
        institutionName = new javax.swing.JLabel();
        institutionEmail = new javax.swing.JLabel();
        institutionType = new javax.swing.JLabel();
        approveBtn = new javax.swing.JButton();
        approveBtn1 = new javax.swing.JButton();

        pendingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel1.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setText("Pending");
        pendingLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setOpaque(true);

        setBackground(new java.awt.Color(234, 234, 234));

        institutionName.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        institutionName.setForeground(new java.awt.Color(51, 51, 51));
        institutionName.setText("General Hospital");

        institutionEmail.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        institutionEmail.setForeground(new java.awt.Color(153, 153, 153));
        institutionEmail.setText("chamau@gmail.com");

        institutionType.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        institutionType.setForeground(new java.awt.Color(153, 153, 153));
        institutionType.setText("Hospital");

        approveBtn.setBackground(new java.awt.Color(204, 255, 204));
        approveBtn.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        approveBtn.setForeground(new java.awt.Color(0, 153, 51));
        approveBtn.setText("Approve");
        approveBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)), null));

        approveBtn1.setBackground(new java.awt.Color(255, 204, 204));
        approveBtn1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        approveBtn1.setForeground(new java.awt.Color(255, 0, 0));
        approveBtn1.setText("Reject");
        approveBtn1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(institutionEmail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(institutionName)
                            .addComponent(institutionType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(approveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(approveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(institutionName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(institutionType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(institutionEmail)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton approveBtn1;
    private javax.swing.JLabel institutionEmail;
    private javax.swing.JLabel institutionName;
    private javax.swing.JLabel institutionType;
    private javax.swing.JLabel pendingLabel1;
    // End of variables declaration//GEN-END:variables
}
