/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.synapse.subpanels;

import com.dev.synapse.classes.BloodRequest;
import com.dev.synapse.classes.UrgentRequests;
import com.dev.synapse.panel.BankPanel;
import com.dev.synapse.panel.HospitalPanel;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author sanukadev
 */
public class UrgentRequestSubPanel extends javax.swing.JPanel {

    private final UrgentRequests urgentRequests;
    private BankPanel bankPanel;

    public UrgentRequestSubPanel(UrgentRequests urgentRequests, BankPanel bankPanel) {
        this.urgentRequests = urgentRequests;
        this.bankPanel = bankPanel;
        initComponents();
        styles();
    }

    public void populateData() {
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("yyyy:MM:dd");
        requestDateLabel.setText(urgentRequests.getRequestDate().format(timeFormatter));

        bloodTypeLabel.setText(urgentRequests.getBloodType());
        urgencyLevelLabel.setText(urgentRequests.getUrgencyLevel());
        insNameLabel.setText(urgentRequests.getInsName());
        requiredUnitsLabel.setText(urgentRequests.getRequiredUnits());
    }

    private void styles() {
        bloodTypeLabel.putClientProperty(FlatClientProperties.STYLE, "arc:999");
        urgencyLevelLabel.putClientProperty(FlatClientProperties.STYLE, "arc:999");
        fullfillBtn.putClientProperty(FlatClientProperties.STYLE, "arc:15");
        detailsBtn.putClientProperty(FlatClientProperties.STYLE, "arc:15");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        detailsBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fullfillBtn = new javax.swing.JButton();
        requiredUnitsLabel = new javax.swing.JLabel();
        urgencyLevelLabel = new javax.swing.JLabel();
        bloodTypeLabel = new javax.swing.JLabel();
        requestDateLabel = new javax.swing.JLabel();
        insNameLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        pendingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel1.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setText("Pending");
        pendingLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setOpaque(true);

        setBackground(new java.awt.Color(234, 234, 234));

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));

        detailsBtn.setBackground(new java.awt.Color(255, 255, 255));
        detailsBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        detailsBtn.setForeground(new java.awt.Color(51, 51, 51));
        detailsBtn.setText("Details");

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Units");

        fullfillBtn.setBackground(new java.awt.Color(204, 0, 0));
        fullfillBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fullfillBtn.setForeground(new java.awt.Color(255, 255, 255));
        fullfillBtn.setText("Fullfill");

        requiredUnitsLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        requiredUnitsLabel.setForeground(new java.awt.Color(153, 153, 153));
        requiredUnitsLabel.setText("4");

        urgencyLevelLabel.setBackground(new java.awt.Color(255, 204, 204));
        urgencyLevelLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        urgencyLevelLabel.setForeground(new java.awt.Color(255, 0, 0));
        urgencyLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setText("High");
        urgencyLevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setOpaque(true);

        bloodTypeLabel.setBackground(new java.awt.Color(204, 255, 204));
        bloodTypeLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        bloodTypeLabel.setForeground(new java.awt.Color(0, 153, 51));
        bloodTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setText("O+");
        bloodTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setOpaque(true);

        requestDateLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        requestDateLabel.setForeground(new java.awt.Color(153, 153, 153));
        requestDateLabel.setText("2025-08-17");

        insNameLabel.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        insNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        insNameLabel.setText("City Medical Center");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(requiredUnitsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(requestDateLabel))
                    .addComponent(insNameLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(fullfillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(detailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDateLabel)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requiredUnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullfillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JButton detailsBtn;
    private javax.swing.JButton fullfillBtn;
    private javax.swing.JLabel insNameLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pendingLabel1;
    private javax.swing.JLabel requestDateLabel;
    private javax.swing.JLabel requiredUnitsLabel;
    private javax.swing.JLabel urgencyLevelLabel;
    // End of variables declaration//GEN-END:variables
}
