/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.synapse.subpanels;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author sanukadev
 */
public class UrgentRequestSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodRequestSubPanel
     */
    public UrgentRequestSubPanel() {
        initComponents();
        styles();
    }

    private void styles() {
        bloodTypeLabel.putClientProperty(FlatClientProperties.STYLE, "arc:999");
        fullfillBtn.putClientProperty(FlatClientProperties.STYLE, "arc:15");
        detailsBtn.putClientProperty(FlatClientProperties.STYLE, "arc:15");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bloodTypeLabel = new javax.swing.JLabel();
        urgencyLevelLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fullfillBtn = new javax.swing.JButton();
        detailsBtn = new javax.swing.JButton();

        pendingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        pendingLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        pendingLabel1.setForeground(new java.awt.Color(255, 153, 0));
        pendingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setText("Pending");
        pendingLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pendingLabel1.setOpaque(true);

        setBackground(new java.awt.Color(234, 234, 234));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("City Medical Center");

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("2025-08-17");

        bloodTypeLabel.setBackground(new java.awt.Color(204, 255, 204));
        bloodTypeLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        bloodTypeLabel.setForeground(new java.awt.Color(0, 153, 51));
        bloodTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setText("O+");
        bloodTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloodTypeLabel.setOpaque(true);

        urgencyLevelLabel.setBackground(new java.awt.Color(255, 204, 204));
        urgencyLevelLabel.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        urgencyLevelLabel.setForeground(new java.awt.Color(255, 0, 0));
        urgencyLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setText("High");
        urgencyLevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        urgencyLevelLabel.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("4");

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Units");

        fullfillBtn.setBackground(new java.awt.Color(204, 0, 0));
        fullfillBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fullfillBtn.setForeground(new java.awt.Color(255, 255, 255));
        fullfillBtn.setText("Fullfill");

        detailsBtn.setBackground(new java.awt.Color(244, 244, 244));
        detailsBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        detailsBtn.setForeground(new java.awt.Color(51, 51, 51));
        detailsBtn.setText("Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addGap(6, 6, 6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(fullfillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urgencyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullfillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JButton detailsBtn;
    private javax.swing.JButton fullfillBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel pendingLabel1;
    private javax.swing.JLabel urgencyLevelLabel;
    // End of variables declaration//GEN-END:variables
}
